server:
  servlet:
    session:
      tracking-modes: cookie  # Only track sessions by cookie
      cookie:
        http-only: true
      timeout: 30m  # 30 minutes
      persistent: true
      store-dir: "session-data"  # Optional location for session data

spring:
  session:
    store-type: none   #  禁用 Spring Session