#spring:
#  session:
#    store-type: none  # 禁用 Spring Session
#server:
#  servlet:
#    session:
#      tracking-modes: cookie # 仅使用 Cookie
#      cookie:
#        http-only: true
#      timeout: 30m # 30 分钟
#      persistent: true
#      store-dir: "session-data" # 可选的会话数据位置